name: CI Apps

on:
  push:

env:
  DOTNET_VERSION: 8.0.x
  APPS_DIR: src/apps

jobs:
  bundle:
    name: Bundle Apps
    uses: ".github/workflows/template-bundle.yml"
    with:
      dir: apps

  ci:
    name: CI
    runs-on: ubuntu-latest
    needs: bundle
    strategy:
      matrix:
        name: ${{ fromJson(needs.bundle_apps.outputs.names) }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build
        working-directory: ${{ env.APPS_DIR }}/${{ matrix.name }}
        run: dotnet build

      - name: Test
        if: always()
        working-directory: src/apps/${{ matrix.name }}
        run: dotnet test --no-build
