name: Testing
on: push

jobs:
  bundle_apps:
    name: Bundle Apps
    runs-on: ubuntu-latest
    outputs:
      names: ${{ steps.list.outputs.result }}
    steps:
      - uses: actions/checkout@v4
      - name: List apps
        id: list
        working-directory: src/apps
        run: echo result=$(find . -maxdepth 1 -type d -not -path "." -printf "%P\n" | jq -R -s -c 'split("\n")[:-1]') >> $GITHUB_OUTPUT
      - name: Debug
        run: echo $GITHUB_OUTPUT

  CI:
    name: CI
    runs-on: ubuntu-latest
    needs: bundle_apps
    strategy:
      matrix:
        name: ${{ fromJson(needs.bundle_apps.outputs.names) }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
      - name: Build & Test
        working-directory: src/apps/${{ matrix.name }}
        run: |
          dotnet build
          dotnet test
