on:
  schedule:
    - cron: "0 5 * * 1"
  workflow_dispatch: {}

jobs:
  tilgangsinfo:
    name: Create Deploy'n'Patch issue for tilgangsinfo
    runs-on: ubuntu-latest

    permissions:
      contents: read
      issues: write
    
    steps:
      - uses: actions/checkout@v4
      - id: create
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/templates/tilgangsinfo-pnd.md
      - uses: monry/actions-add-issue-to-project@v2
        with:
          # Personal Access Token that with `repo`, `project`, `org:read` and `org:write` are granted.
          github-token: ${{ secrets.ASSIGN_PROJECT_TOKEN }}
          project-owner: 'Altinn'
          project-number: 75
          issue-repository: '${{ github.repository }}'
          issue-number: ${{ steps.create.outputs.number }}
