name: Create Deploy'n'Patch Issues

on:
  schedule:
    - cron: "0 5 * * 1"
  workflow_dispatch: {}

jobs:
  tilgangsinfo:
    name: Create Deploy'n'Patch issue for tilgangsinfo
    runs-on: ubuntu-latest

    permissions:
      contents: read
      issues: write

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 20

      - uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4
        with:
          version: 9
          run_install: |
            - cwd: .github/scripts
              args: [--frozen-lockfile]
            - args: [--global, tsx]

      - id: create
        name: Create issue
        uses: JasonEtco/create-an-issue@1b14a70e4d8dc185e5cc76d3bec9eab20257b2c5 # v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/templates/tilgangsinfo-pnd.md

      - name: Add issue to project
        env:
          GITHUB_TOKEN: ${{ secrets.ASSIGN_PROJECT_TOKEN }}
          GITHUB_ISSUE_NUMBER: ${{ steps.create.outputs.number }}
          GITHUB_PROJECT_NUMBER: 75
          # set status = "In progress"
          GITHUB_PROJECT_FIELDS: |
            {
              "PVTSSF_lADOAFrH7M4ALF9LzgHEmZw": { "singleSelectOptionId": "e4413b57" }
            }
        run: tsx ./.github/scripts/add-to-project.mts

  tilgangsstyring:
    name: Create Deploy'n'Patch issue for tilgangsstyring
    runs-on: ubuntu-latest

    permissions:
      contents: read
      issues: write

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 20

      - uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4
        with:
          version: 9
          run_install: |
            - cwd: .github/scripts
              args: [--frozen-lockfile]
            - args: [--global, tsx]

      - id: create
        name: Create issue
        uses: JasonEtco/create-an-issue@1b14a70e4d8dc185e5cc76d3bec9eab20257b2c5 # v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/templates/tilgangsstyring-pnd.md

      - name: Add issue to project
        env:
          GITHUB_TOKEN: ${{ secrets.ASSIGN_PROJECT_TOKEN }}
          GITHUB_ISSUE_NUMBER: ${{ steps.create.outputs.number }}
          GITHUB_PROJECT_NUMBER: 50
          # set status = "In progress"
          GITHUB_PROJECT_FIELDS: |
            {
              "PVTSSF_lADOAFrH7M4AI9-nzgFibRI": { "singleSelectOptionId": "47fc9ee4" }
            }
        run: tsx ./.github/scripts/add-to-project.mts
