name: Pack and publish Altinn.Authorization.ABAC nuget package

on:
  pull_request:
    branches: infrastructure/publish-nuget-action
  release:
    types:
      - published

jobs:
  build-pack:
    #if: startsWith(github.ref, 'refs/tags/Altinn.Authorization.ABAC-')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            2.0.x

      - name: Install deps
        working-directory: src/Altinn.Authorization.ABAC
        run: |
          dotnet restore

      - name: Build
        working-directory: src/Altinn.Authorization.ABAC
        run: |
          dotnet build --configuration Release --no-restore -p:Deterministic=true -p:BuildNumber=${{ github.run_number }}

      - name: Pack Altinn.Authorization.ABAC
        working-directory: src/Altinn.Authorization.ABAC
        run: |
          dotnet pack --configuration Release --no-restore --no-build -p:Deterministic=true -p:BuildNumber=${{ github.run_number }}
           
      - name: publish Altinn.Authorization.ABAC
        working-directory: src/Altinn.Authorization.ABAC
        run: |
          dotnet nuget push bin/Release/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
