name: Pack and publish Altinn.Authorization.ABAC nuget package

on:
  pull_request:
    paths: src/Altinn.Authorization.ABAC
  push:
    branches: infrastructure/publish-nuget-action    
    tags:
      - Altinn.Authorization.ABAC-*
  release:
    types:
      - published

jobs:
  build-pack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            2.0.x

      - name: Build
        working-directory: src/Altinn.Authorization.ABAC
        run: |
          dotnet build --configuration Release

      - name: Pack Altinn.Authorization.ABAC
        working-directory: src/Altinn.Authorization.ABAC
        run: |
          dotnet pack --configuration Release --no-build

      - name: Create artifact
        uses: actions/upload-artifact@v4
        with:
          name: nuget package
          path: src/Altinn.Authorization.ABAC/bin/Release/*.nupkg
          if-no-files-found: error
           
      - name: publish Altinn.Authorization.ABAC
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        working-directory: src/Altinn.Authorization.ABAC
        run: |
          dotnet nuget push bin/Release/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ env.NUGET_API_KEY }}
